version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./scripts/createDb.sh:/docker-entrypoint-initdb.d/createDb.sh
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
    env_file: .env
    environment:
      DB_HOST: postgres
    restart: always